"""initial durable schema

Revision ID: 0001
Revises:
Create Date: 2026-06-25 23:56:29.491760
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_traces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_type", sa.String(length=80), nullable=False),
        sa.Column("subject_type", sa.String(length=80), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=120), nullable=False),
        sa.Column("features_json", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("decision", sa.Boolean(), nullable=False),
        sa.Column("outcome_score", sa.Float(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decision_traces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decision_traces_decision_type"), ["decision_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_decision_traces_policy_version"), ["policy_version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_decision_traces_subject_id"), ["subject_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decision_traces_subject_type"), ["subject_type"], unique=False)
        batch_op.create_index(
            "ix_decision_traces_type_created", ["decision_type", "created_at"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=250), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("ingest_key", sa.String(length=128), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("parser_version", sa.String(length=80), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingest_key", name="uq_documents_ingest_key"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_fetched_at"), ["fetched_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_ingest_key"), ["ingest_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_source"), ["source"], unique=False)
        batch_op.create_index("ix_documents_source_fetched", ["source", "fetched_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_status"), ["status"], unique=False)

    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("normalised_name", sa.String(length=250), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalised_name", "kind", name="uq_entities_normalised_kind"),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entities_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_normalised_name"), ["normalised_name"], unique=False)

    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(length=120), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("evaluator_type", sa.String(length=80), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "target_type",
            "target_id",
            "metric_name",
            "evaluator_type",
            name="uq_evaluation_target_metric_evaluator",
        ),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index("ix_evaluations_metric_created", ["metric_name", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluations_metric_name"), ["metric_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluations_target_id"), ["target_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluations_target_type"), ["target_type"], unique=False)

    op.create_table(
        "event_cursors",
        sa.Column("loop_name", sa.String(length=120), nullable=False),
        sa.Column("last_event_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("loop_name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("source_loop", sa.String(length=120), nullable=True),
        sa.Column("correlation_id", sa.String(length=120), nullable=False),
        sa.Column("parent_event_id", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=250), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_events_idempotency_key"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_correlation_id"), ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index("ix_events_type_id", ["event_type", "id"], unique=False)

    op.create_table(
        "hypotheses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("claim_hash", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=250), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "claim_hash", name="uq_hypotheses_scope_hash"),
    )
    with op.batch_alter_table("hypotheses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hypotheses_claim_hash"), ["claim_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_hypotheses_scope"), ["scope"], unique=False)
        batch_op.create_index(batch_op.f("ix_hypotheses_status"), ["status"], unique=False)
        batch_op.create_index("ix_hypotheses_status_updated", ["status", "updated_at"], unique=False)

    op.create_table(
        "loop_leases",
        sa.Column("loop_name", sa.String(length=120), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("loop_name"),
    )
    with op.batch_alter_table("loop_leases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_loop_leases_lease_until"), ["lease_until"], unique=False)

    op.create_table(
        "loop_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("loop_name", sa.String(length=120), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("consumed_events", sa.Integer(), nullable=False),
        sa.Column("emitted_events", sa.Integer(), nullable=False),
        sa.Column("created_records_json", sa.JSON(), nullable=False),
        sa.Column("notes_json", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("loop_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_loop_runs_loop_name"), ["loop_name"], unique=False)
        batch_op.create_index("ix_loop_runs_loop_started", ["loop_name", "started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_loop_runs_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_loop_runs_status"), ["status"], unique=False)

    op.create_table(
        "mission_charters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("mission", sa.Text(), nullable=False),
        sa.Column("domains_json", sa.JSON(), nullable=False),
        sa.Column("anti_goals_json", sa.JSON(), nullable=False),
        sa.Column("success_criteria_json", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mission_charters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mission_charters_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_mission_charters_version"), ["version"], unique=False)

    op.create_table(
        "policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("parent_policy_id", sa.Integer(), nullable=True),
        sa.Column("policy_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("evaluation_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="uq_policy_version"),
    )
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policies_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_policies_version"), ["version"], unique=False)

    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_name"), ["name"], unique=True)

    op.create_table(
        "system_state",
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_doc_idx"),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chunks_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chunks_status"), ["status"], unique=False)
        batch_op.create_index("ix_chunks_status_attempts", ["status", "attempts"], unique=False)
        batch_op.create_index(batch_op.f("ix_chunks_text_hash"), ["text_hash"], unique=False)

    op.create_table(
        "experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_policy_id", sa.Integer(), nullable=True),
        sa.Column("candidate_policy_id", sa.Integer(), nullable=True),
        sa.Column("replay_result_json", sa.JSON(), nullable=False),
        sa.Column("shadow_result_json", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_policy_id"],
            ["policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_policy_id"],
            ["policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experiments_decision"), ["decision"], unique=False)

    op.create_table(
        "source_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=250), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("last_document_id", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_uri", name="uq_source_items_source_uri"),
    )
    with op.batch_alter_table("source_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_items_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_items_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_items_status"), ["status"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=250), nullable=False),
        sa.Column("trigger_event_id", sa.Integer(), nullable=True),
        sa.Column("hypothesis_id", sa.Integer(), nullable=True),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("max_cost", sa.Float(), nullable=False),
        sa.Column("max_depth", sa.Integer(), nullable=False),
        sa.Column("tool_budget", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["hypothesis_id"], ["hypotheses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["trigger_event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_tasks_idempotency_key"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_available_at"), ["available_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_hypothesis_id"), ["hypothesis_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_idempotency_key"), ["idempotency_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)
        batch_op.create_index("ix_tasks_status_priority", ["status", "priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_task_type"), ["task_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_trigger_event_id"), ["trigger_event_id"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("linked_hypothesis_id", sa.Integer(), nullable=True),
        sa.Column("linked_task_id", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["linked_hypothesis_id"], ["hypotheses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["linked_task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "artifact_type", "linked_hypothesis_id", "version", name="uq_artifact_type_hypothesis_version"
        ),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_artifact_type"), ["artifact_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_artifacts_linked_hypothesis_id"), ["linked_hypothesis_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_artifacts_linked_task_id"), ["linked_task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_status"), ["status"], unique=False)
        batch_op.create_index("ix_artifacts_type_created", ["artifact_type", "created_at"], unique=False)

    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("chunk_id", sa.Integer(), nullable=True),
        sa.Column("claim_hash", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("subject", sa.String(length=250), nullable=True),
        sa.Column("predicate", sa.String(length=250), nullable=True),
        sa.Column("object", sa.String(length=250), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "claim_hash", name="uq_claims_chunk_hash"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claims_chunk_id"), ["chunk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_claim_hash"), ["claim_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_document_id"), ["document_id"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("policy_version", sa.String(length=120), nullable=True),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column("tools_used_json", sa.JSON(), nullable=False),
        sa.Column("input_context_json", sa.JSON(), nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("chunk_id", sa.Integer(), nullable=True),
        sa.Column("signal_hash", sa.String(length=128), nullable=False),
        sa.Column("entity", sa.String(length=250), nullable=True),
        sa.Column("signal_type", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("novelty_score", sa.Float(), nullable=False),
        sa.Column("impact_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "signal_hash", name="uq_signals_chunk_hash"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signals_chunk_id"), ["chunk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_entity"), ["entity"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_signal_hash"), ["signal_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_signal_type"), ["signal_type"], unique=False)
        batch_op.create_index("ix_signals_type_created", ["signal_type", "created_at"], unique=False)

    op.create_table(
        "artifact_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifact_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifact_feedback_artifact_id"), ["artifact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifact_feedback_verdict"), ["verdict"], unique=False)
        batch_op.create_index("ix_feedback_artifact_created", ["artifact_id", "created_at"], unique=False)

    op.create_table(
        "evidence_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hypothesis_id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("chunk_id", sa.Integer(), nullable=True),
        sa.Column("evidence_hash", sa.String(length=128), nullable=False),
        sa.Column("stance", sa.String(length=30), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("provenance", sa.String(length=80), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hypothesis_id"], ["hypotheses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hypothesis_id", "evidence_hash", name="uq_evidence_hypothesis_hash"),
    )
    with op.batch_alter_table("evidence_edges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_edges_chunk_id"), ["chunk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_edges_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_edges_evidence_hash"), ["evidence_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_edges_hypothesis_id"), ["hypothesis_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_edges_signal_id"), ["signal_id"], unique=False)
        batch_op.create_index("ix_evidence_hypothesis_stance", ["hypothesis_id", "stance"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_edges", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_hypothesis_stance")
        batch_op.drop_index(batch_op.f("ix_evidence_edges_signal_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_edges_hypothesis_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_edges_evidence_hash"))
        batch_op.drop_index(batch_op.f("ix_evidence_edges_document_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_edges_chunk_id"))

    op.drop_table("evidence_edges")
    with op.batch_alter_table("artifact_feedback", schema=None) as batch_op:
        batch_op.drop_index("ix_feedback_artifact_created")
        batch_op.drop_index(batch_op.f("ix_artifact_feedback_verdict"))
        batch_op.drop_index(batch_op.f("ix_artifact_feedback_artifact_id"))

    op.drop_table("artifact_feedback")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_type_created")
        batch_op.drop_index(batch_op.f("ix_signals_signal_type"))
        batch_op.drop_index(batch_op.f("ix_signals_signal_hash"))
        batch_op.drop_index(batch_op.f("ix_signals_entity"))
        batch_op.drop_index(batch_op.f("ix_signals_document_id"))
        batch_op.drop_index(batch_op.f("ix_signals_created_at"))
        batch_op.drop_index(batch_op.f("ix_signals_chunk_id"))

    op.drop_table("signals")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_task_id"))

    op.drop_table("runs")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_document_id"))
        batch_op.drop_index(batch_op.f("ix_claims_claim_hash"))
        batch_op.drop_index(batch_op.f("ix_claims_chunk_id"))

    op.drop_table("claims")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index("ix_artifacts_type_created")
        batch_op.drop_index(batch_op.f("ix_artifacts_status"))
        batch_op.drop_index(batch_op.f("ix_artifacts_linked_task_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_linked_hypothesis_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_content_hash"))
        batch_op.drop_index(batch_op.f("ix_artifacts_artifact_type"))

    op.drop_table("artifacts")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_trigger_event_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_task_type"))
        batch_op.drop_index("ix_tasks_status_priority")
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_tasks_hypothesis_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_available_at"))

    op.drop_table("tasks")
    with op.batch_alter_table("source_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_items_status"))
        batch_op.drop_index(batch_op.f("ix_source_items_source"))
        batch_op.drop_index(batch_op.f("ix_source_items_fingerprint"))

    op.drop_table("source_items")
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiments_decision"))

    op.drop_table("experiments")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunks_text_hash"))
        batch_op.drop_index("ix_chunks_status_attempts")
        batch_op.drop_index(batch_op.f("ix_chunks_status"))
        batch_op.drop_index(batch_op.f("ix_chunks_document_id"))

    op.drop_table("chunks")
    op.drop_table("system_state")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_name"))

    op.drop_table("sources")
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policies_version"))
        batch_op.drop_index(batch_op.f("ix_policies_status"))

    op.drop_table("policies")
    with op.batch_alter_table("mission_charters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mission_charters_version"))
        batch_op.drop_index(batch_op.f("ix_mission_charters_active"))

    op.drop_table("mission_charters")
    with op.batch_alter_table("loop_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loop_runs_status"))
        batch_op.drop_index(batch_op.f("ix_loop_runs_started_at"))
        batch_op.drop_index("ix_loop_runs_loop_started")
        batch_op.drop_index(batch_op.f("ix_loop_runs_loop_name"))

    op.drop_table("loop_runs")
    with op.batch_alter_table("loop_leases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_loop_leases_lease_until"))

    op.drop_table("loop_leases")
    with op.batch_alter_table("hypotheses", schema=None) as batch_op:
        batch_op.drop_index("ix_hypotheses_status_updated")
        batch_op.drop_index(batch_op.f("ix_hypotheses_status"))
        batch_op.drop_index(batch_op.f("ix_hypotheses_scope"))
        batch_op.drop_index(batch_op.f("ix_hypotheses_claim_hash"))

    op.drop_table("hypotheses")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_type_id")
        batch_op.drop_index(batch_op.f("ix_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_events_correlation_id"))

    op.drop_table("events")
    op.drop_table("event_cursors")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_target_type"))
        batch_op.drop_index(batch_op.f("ix_evaluations_target_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_metric_name"))
        batch_op.drop_index("ix_evaluations_metric_created")

    op.drop_table("evaluations")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_normalised_name"))
        batch_op.drop_index(batch_op.f("ix_entities_name"))

    op.drop_table("entities")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_status"))
        batch_op.drop_index("ix_documents_source_fetched")
        batch_op.drop_index(batch_op.f("ix_documents_source"))
        batch_op.drop_index(batch_op.f("ix_documents_ingest_key"))
        batch_op.drop_index(batch_op.f("ix_documents_fetched_at"))
        batch_op.drop_index(batch_op.f("ix_documents_content_hash"))

    op.drop_table("documents")
    with op.batch_alter_table("decision_traces", schema=None) as batch_op:
        batch_op.drop_index("ix_decision_traces_type_created")
        batch_op.drop_index(batch_op.f("ix_decision_traces_subject_type"))
        batch_op.drop_index(batch_op.f("ix_decision_traces_subject_id"))
        batch_op.drop_index(batch_op.f("ix_decision_traces_policy_version"))
        batch_op.drop_index(batch_op.f("ix_decision_traces_decision_type"))

    op.drop_table("decision_traces")
    # ### end Alembic commands ###
